### ISSUE TITLE
Agregar funcionalidad a la lista de usuarios

### ISSUE THREAD

**Issue by GNico** [jmartty/taller2server#13]
A la lista de usuarios devuelta al hacer GET (/usuarios) debe agregarse un atributo binario que indique si el usuario que realiza el request tiene mensajes nuevos provenientes de cada usuario distinto.                                                

Ej:
[ {"id" = "pedro", "nombre" = "pepe", "estado" = "conectado", "nuevosmsg" = true }]

Se setea en true tras mandar un mensaje y en false despues de haber accedido a la conversacion

**Comment by jmartty** [comment]
Se implementó la funcionalidad en aa1f8b74c87e9a1a31f436c9035817fb9fa10ec2
