### ISSUE TITLE
Modificacion en el protocolo REST

### ISSUE THREAD

**Issue by GNico** [jmartty/taller2server#14]
Recurso usuario: debe contener la siguiente informacion: nombre_, password_, ubicacion, foto_, fyh de ultimo acceso, telefono, fecha de nacimiento
(_requerido, lo demas puede ser null)

Accion Modificar usuario: se debe verificar el password reingresado por el cliente y pasado por parametro del request.

**Comment by jmartty** [comment]
string:
nombre, foto, ultimoacceso, telefono, email;

**Comment by jmartty** [comment]
Implementado en commit 74a2cd31e773a595c2a507ac509345d20403884d

**Comment by Myacobucci** [comment]
Modelado en Sphinx en 9d1316bb3d566eba92315a4977f6795f1de6371a
