### ISSUE TITLE
Diseñar el protocolo REST para comunicacion entre cliente y servidor

### ISSUE THREAD

**Issue by jmartty** [jmartty/taller2server#3]
Debe seguir las especificaciones dadas por el la consigna del TP.

La documentación debe incluir todos los casos de uso, cada uno con su correspondiente URI, metodo, descripcion de body data, response codes para cada escenario y cualquier aclaración necesaria

**Comment by GNico** [comment]
Se publico el documento sobre la primer version del protocolo REST que estaremos usando. Se especifican los recursos disponibles, la forma de acceder a ellos y la respuesta del servidor. 

Documento PDF:  docs/Protocolo-REST-v1.1.pdf

Commit (master branch): https://github.com/jmartty/taller2server/commit/abac4ed2cad2a3b914c3fb521b729979415bedaf
