### ISSUE TITLE
Construir Cmake

### ISSUE THREAD

**Issue by Myacobucci** [jmartty/taller2server#4]
Implementar el Cmake para el proyecto

**Comment by jmartty** [comment]
Se migró de Makefile a CMakeLists.txt. Se incluyeron las opciones de build, test y run en un script build.sh en el root del proyecto que unifica la compilacion, corrida y testeo del proyecto incluyendo el pasaje de argumentos a los binarios correspondientes

6b96a8ef940e47eac3252431f46ee817d874eb1a
