### ISSUE TITLE
Escribir tests unitarios externos para validar el funcionamiento correcto del la API

### ISSUE THREAD

**Issue by jmartty** [jmartty/taller2server#5]
Se debe seguir la ultima version del protocolo REST especificado en la carpeta "docs/" (versión al momento: https://github.com/jmartty/taller2server/blob/master/docs/Protocolo-REST-v1.2.pdf)

Información adicional:
- Se recomienda hacerlos en python, usando la libreria request y requests. Ejemplos que vimos en clase: https://github.com/gfusca/python_rest_api_example
- Debe testear: autenticacion, listado de usuarios, ver un usuario, crear un usuario, modificar perfil propio de usuario, ver una conversación y agregar un mensaje a una conversacion

**Comment by jmartty** [comment]
Se actualizó la documentación del protocolo a la versión 1.3: https://github.com/jmartty/taller2server/blob/master/docs/Protocolo-REST-v1.3.pdf

**Comment by Myacobucci** [comment]
Se implementaron los test unitarios para validar el funcionamiento correcto de la API a través de la librería request de python. 

Archivos: Test_rest.py y run_test.py

Commit: 74fbeabfdd204b27f6226f69f8a760fd07611fd1
